openapi: 3.0.3
info:
  title: Product API
  description: API for managing products
  version: 1.0.0
servers:
  - url: 'https://localhost:9002'
paths:
  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all products
      operationId: getAllProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductModel'
    post:
      summary: Create a new product
      description: Add a new product to the system
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
      responses:
        '201':
          description: Product created successfully
        '400':
          description: Invalid input or product creation failed
  /products/{id}:
    get:
      summary: Get a product by ID
      description: Retrieve a specific product by its ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductModel'
        '404':
          description: Product not found
    put:
      summary: Update an existing product
      description: Modify a product by its ID
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
      responses:
        '200':
          description: Product updated successfully
        '400':
          description: Invalid input or mismatched ID
        '404':
          description: Product not found
    delete:
      summary: Delete a product by ID
      description: Remove a product from the system
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
      responses:
        '204':
          description: Product deleted successfully
        '404':
          description: Product not found
components:
  schemas:
    ProductModel:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the product
        name:
          type: string
          description: The name of the product
        price:
          type: number
          format: float
          description: The price of the product
        description:
          type: string
          description: A description of the product
      required:
        - id
        - name
        - price
